language: elixir
elixir:
  - 1.5
  - 1.6
otp_release:
  - 19.3
  - 20.2
env:
  - STRICT=true
matrix:
  exclude:
    - elixir: 1.5
      otp_release: 19.3
    - elixir: 1.6
      otp_release: 20.2
script:
  - if [ "$STRICT" = "true" ]; then mix compile --warnings-as-errors; fi
  - mix test
  - if [ "$STRICT" = "true" ]; then mix dialyzer; fi
  - if [ "$STRICT" = "true" ]; then mix format --dry-run --check-formatted; fi
cache:
  directories:
    - .mix
    - _build
